import random
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.core.deps import get_current_user
from app.database import get_db
from app.models.interview import InterviewMessage, InterviewSession, InterviewStatus
from app.models.mock_interview import MockInterviewLoop
from app.models.problem import Difficulty, Problem
from app.models.submission import Submission, SubmissionStatus
from app.models.system_design import SystemDesignAttempt, SystemDesignCase
from app.models.user import User
from app.schemas.interview import (
    AnswerRequest, AnswerResponse, BehavioralAnswerRequest, InterviewMessageOut, InterviewReport,
    MockLoopReportOut, MockLoopStartResponse, MockLoopStateOut,
    StartInterviewRequest, StartInterviewResponse,
)
from app.services.interview.behavioral import BEHAVIORAL_QUESTIONS, score_behavioral_answer
from app.services.interview.simulator import first_stage, next_stage, stages_for
from app.services.llm.local_llm import LocalLLMUnavailable, generate as llm_generate

router = APIRouter(prefix="/interviews", tags=["interviews"])


@router.post("/start", response_model=StartInterviewResponse)
def start_interview(
    payload: StartInterviewRequest, current_user: User = Depends(get_current_user), db: Session = Depends(get_db),
):
    problem_id = None
    case_id = None
    if payload.type == "dsa":
        if not payload.problem_slug:
            raise HTTPException(status_code=400, detail="problem_slug required for dsa interview")
        problem = db.query(Problem).filter(Problem.slug == payload.problem_slug).first()
        if not problem:
            raise HTTPException(status_code=404, detail="Problem not found")
        problem_id = problem.id
    elif payload.type == "system_design":
        if not payload.case_slug:
            raise HTTPException(status_code=400, detail="case_slug required for system_design interview")
        case = db.query(SystemDesignCase).filter(SystemDesignCase.slug == payload.case_slug).first()
        if not case:
            raise HTTPException(status_code=404, detail="Case not found")
        case_id = case.id
    else:
        raise HTTPException(status_code=400, detail="type must be 'dsa' or 'system_design'")

    stage_key, question = first_stage(payload.type)
    session = InterviewSession(
        user_id=current_user.id, type=payload.type, problem_id=problem_id, case_id=case_id, stage=stage_key,
    )
    db.add(session)
    db.flush()
    msg = InterviewMessage(session_id=session.id, role="interviewer", stage=stage_key, content=question)
    db.add(msg)
    db.commit()

    return StartInterviewResponse(
        session_id=session.id, stage=stage_key,
        messages=[InterviewMessageOut(role="interviewer", stage=stage_key, content=question)],
    )


@router.post("/{session_id}/answer", response_model=AnswerResponse)
def answer(
    session_id: str, payload: AnswerRequest,
    current_user: User = Depends(get_current_user), db: Session = Depends(get_db),
):
    session = db.query(InterviewSession).filter(
        InterviewSession.id == session_id, InterviewSession.user_id == current_user.id
    ).first()
    if not session or session.status != InterviewStatus.active:
        raise HTTPException(status_code=404, detail="Active interview session not found")

    answered_stage = session.stage
    db.add(InterviewMessage(session_id=session.id, role="candidate", stage=answered_stage, content=payload.content))

    # Best-effort: a short reaction to what the candidate actually said, generated by the
    # local LLM. Purely cosmetic -- stage progression and the final coverage score below
    # never depend on this, so an unavailable/slow model degrades to no commentary, not a
    # broken interview.
    commentary = None
    try:
        commentary = llm_generate(
            system_prompt=(
                "You are a technical interviewer. React briefly (1-2 sentences) to the candidate's answer -- "
                "acknowledge what they said or note a gap -- without revealing the correct answer."
            ),
            user_prompt=f"Interview stage: {answered_stage}\nCandidate said: {payload.content}",
            max_tokens=90,
        )
    except LocalLLMUnavailable:
        pass

    nxt = next_stage(session.type.value, session.stage)
    messages_out = []
    if nxt is None or nxt[0] == "done":
        session.status = InterviewStatus.completed
        session.ended_at = datetime.utcnow()
        finished = True
        stage_out = "done"
        closing = "Interview complete. Review your transcript for a stage-by-stage report."
        db.add(InterviewMessage(session_id=session.id, role="interviewer", stage="done", content=closing))
        messages_out.append(InterviewMessageOut(role="interviewer", stage="done", content=closing))
    else:
        stage_key, question = nxt
        session.stage = stage_key
        finished = False
        stage_out = stage_key
        db.add(InterviewMessage(session_id=session.id, role="interviewer", stage=stage_key, content=question))
        messages_out.append(InterviewMessageOut(role="interviewer", stage=stage_key, content=question))

    db.commit()
    return AnswerResponse(stage=stage_out, finished=finished, messages=messages_out, commentary=commentary)


@router.get("/{session_id}/report", response_model=InterviewReport)
def report(session_id: str, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    session = db.query(InterviewSession).filter(
        InterviewSession.id == session_id, InterviewSession.user_id == current_user.id
    ).first()
    if not session:
        raise HTTPException(status_code=404, detail="Interview session not found")

    msgs = db.query(InterviewMessage).filter(InterviewMessage.session_id == session.id).order_by(
        InterviewMessage.created_at.asc()
    ).all()
    total_stages = len(stages_for(session.type.value)) - 1  # exclude terminal "done"
    candidate_stages = {m.stage for m in msgs if m.role == "candidate"}
    coverage = round(len(candidate_stages) / total_stages, 3) if total_stages else 0.0

    summary = (
        f"Answered {len(candidate_stages)}/{total_stages} interview stages. "
        + ("Full coverage of the interview loop." if coverage >= 1.0 else
           "Some stages were skipped -- in a real interview, an unaddressed stage reads as an unaddressed risk.")
    )

    return InterviewReport(
        stages_completed=len(candidate_stages), total_stages=total_stages,
        transcript=[InterviewMessageOut(role=m.role, stage=m.stage, content=m.content) for m in msgs],
        coverage_score=coverage, summary=summary,
    )


# --- Full Mock Interview Loop: one DSA problem + one System Design case + one
# behavioral question, chained into a single timed session. Deliberately
# reuses the app's own already-verified /problems/{slug}/submit and
# /system-design/cases/{slug}/attempt endpoints for real grading rather than
# re-implementing correctness checking a second time -- see
# models/mock_interview.py's docstring for why. Only the behavioral round
# needed genuinely new verification logic.

@router.post("/full-loop/start", response_model=MockLoopStartResponse)
def start_full_loop(current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    problem = (
        db.query(Problem).filter(Problem.difficulty == Difficulty.medium)
        .order_by(func.random()).first()
    ) or db.query(Problem).order_by(func.random()).first()
    if not problem:
        raise HTTPException(status_code=503, detail="No problems seeded yet.")

    case = (
        db.query(SystemDesignCase).filter(SystemDesignCase.scale_tier == "growth")
        .order_by(func.random()).first()
    ) or db.query(SystemDesignCase).order_by(func.random()).first()
    if not case:
        raise HTTPException(status_code=503, detail="No system design cases seeded yet.")

    question = random.choice(BEHAVIORAL_QUESTIONS)

    loop = MockInterviewLoop(
        user_id=current_user.id, stage="dsa",
        dsa_problem_id=problem.id, sd_case_id=case.id, behavioral_question=question,
    )
    db.add(loop)
    db.commit()

    return MockLoopStartResponse(
        loop_id=loop.id, stage=loop.stage,
        dsa_problem_slug=problem.slug, dsa_problem_title=problem.title,
        sd_case_slug=case.slug, sd_case_title=case.title,
        behavioral_question=question,
    )


def _get_loop(loop_id: str, user_id: str, db: Session) -> MockInterviewLoop:
    loop = db.query(MockInterviewLoop).filter(MockInterviewLoop.id == loop_id, MockInterviewLoop.user_id == user_id).first()
    if not loop:
        raise HTTPException(status_code=404, detail="Mock interview loop not found")
    return loop


@router.get("/full-loop/{loop_id}", response_model=MockLoopStateOut)
def get_full_loop_state(loop_id: str, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    loop = _get_loop(loop_id, current_user.id, db)
    problem = db.query(Problem).filter(Problem.id == loop.dsa_problem_id).first()
    case = db.query(SystemDesignCase).filter(SystemDesignCase.id == loop.sd_case_id).first()
    dsa_sub = db.query(Submission).filter(Submission.id == loop.dsa_submission_id).first() if loop.dsa_submission_id else None
    sd_attempt = db.query(SystemDesignAttempt).filter(SystemDesignAttempt.id == loop.sd_attempt_id).first() if loop.sd_attempt_id else None

    return MockLoopStateOut(
        loop_id=loop.id, stage=loop.stage,
        dsa_problem_slug=problem.slug, dsa_submitted=dsa_sub is not None,
        dsa_passed=(dsa_sub.status == SubmissionStatus.passed) if dsa_sub else None,
        sd_case_slug=case.slug, sd_submitted=sd_attempt is not None,
        sd_score=sd_attempt.score if sd_attempt else None,
        behavioral_question=loop.behavioral_question, behavioral_submitted=loop.behavioral_score is not None,
    )


@router.post("/full-loop/{loop_id}/sync-dsa", response_model=MockLoopStateOut)
def sync_dsa_round(loop_id: str, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    """Call after submitting through the normal /problems/{slug}/submit flow
    for this loop's linked problem -- links the resulting real Submission
    (whatever its actual result was) to this loop and advances to the System
    Design round. Does not require a PASSED result: a real onsite doesn't
    let you retry until you pass, either."""
    loop = _get_loop(loop_id, current_user.id, db)
    if loop.stage != "dsa":
        raise HTTPException(status_code=400, detail=f"This loop is on the '{loop.stage}' round, not 'dsa'.")

    submission = (
        db.query(Submission)
        .filter(Submission.user_id == current_user.id, Submission.problem_id == loop.dsa_problem_id)
        .order_by(Submission.created_at.desc()).first()
    )
    if not submission:
        raise HTTPException(status_code=400, detail="Submit a solution to the linked DSA problem first.")

    loop.dsa_submission_id = submission.id
    loop.stage = "system_design"
    db.commit()
    return get_full_loop_state(loop_id, current_user, db)


@router.post("/full-loop/{loop_id}/sync-system-design", response_model=MockLoopStateOut)
def sync_sd_round(loop_id: str, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    """Same pattern as sync-dsa: links the real SystemDesignAttempt already
    created via /system-design/cases/{slug}/attempt for this loop's case."""
    loop = _get_loop(loop_id, current_user.id, db)
    if loop.stage != "system_design":
        raise HTTPException(status_code=400, detail=f"This loop is on the '{loop.stage}' round, not 'system_design'.")

    attempt = (
        db.query(SystemDesignAttempt)
        .filter(SystemDesignAttempt.user_id == current_user.id, SystemDesignAttempt.case_id == loop.sd_case_id)
        .order_by(SystemDesignAttempt.created_at.desc()).first()
    )
    if not attempt:
        raise HTTPException(status_code=400, detail="Submit a design for the linked System Design case first.")

    loop.sd_attempt_id = attempt.id
    loop.stage = "behavioral"
    db.commit()
    return get_full_loop_state(loop_id, current_user, db)


@router.post("/full-loop/{loop_id}/behavioral-answer", response_model=MockLoopStateOut)
def submit_behavioral_answer(
    loop_id: str, payload: BehavioralAnswerRequest,
    current_user: User = Depends(get_current_user), db: Session = Depends(get_db),
):
    loop = _get_loop(loop_id, current_user.id, db)
    if loop.stage != "behavioral":
        raise HTTPException(status_code=400, detail=f"This loop is on the '{loop.stage}' round, not 'behavioral'.")

    result = score_behavioral_answer(payload.answer)
    loop.behavioral_answer = payload.answer
    loop.behavioral_score = result["star_score"]
    loop.behavioral_matched_parts = result["matched_parts"]
    loop.stage = "completed"
    loop.completed_at = datetime.utcnow()
    db.commit()
    return get_full_loop_state(loop_id, current_user, db)


@router.get("/full-loop/{loop_id}/report", response_model=MockLoopReportOut)
def get_full_loop_report(loop_id: str, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    loop = _get_loop(loop_id, current_user.id, db)
    if loop.stage != "completed":
        raise HTTPException(status_code=400, detail="Complete all three rounds before viewing the report.")

    problem = db.query(Problem).filter(Problem.id == loop.dsa_problem_id).first()
    case = db.query(SystemDesignCase).filter(SystemDesignCase.id == loop.sd_case_id).first()
    dsa_sub = db.query(Submission).filter(Submission.id == loop.dsa_submission_id).first()
    sd_attempt = db.query(SystemDesignAttempt).filter(SystemDesignAttempt.id == loop.sd_attempt_id).first()
    behavioral = score_behavioral_answer(loop.behavioral_answer)

    dsa_passed = dsa_sub.status == SubmissionStatus.passed if dsa_sub else None
    parts = []
    parts.append("passed the DSA round" if dsa_passed else "did not pass the DSA round")
    parts.append(f"scored {round((sd_attempt.score if sd_attempt else 0) * 100)}% on the System Design critique")
    parts.append(f"gave a {behavioral['tier'].replace('_', ' ').lower()} behavioral answer")
    overall_summary = "In this mock loop, you " + ", ".join(parts) + "."

    return MockLoopReportOut(
        dsa_problem_title=problem.title, dsa_passed=dsa_passed,
        dsa_passed_count=dsa_sub.passed_count if dsa_sub else None,
        dsa_total_count=dsa_sub.total_count if dsa_sub else None,
        sd_case_title=case.title, sd_score=sd_attempt.score if sd_attempt else None,
        sd_missing_components=(sd_attempt.feedback or {}).get("missing_components", []) if sd_attempt else [],
        sd_unjustified_components=(sd_attempt.feedback or {}).get("unjustified_components", []) if sd_attempt else [],
        behavioral_question=loop.behavioral_question, behavioral_tier=behavioral["tier"],
        behavioral_coaching_tip=behavioral["coaching_tip"], behavioral_star_score=behavioral["star_score"],
        overall_summary=overall_summary,
    )
